[build]
  publish = "."
  functions = "netlify/functions"
[build]
  publish = "."             # your static files are in the root
  functions = "netlify/functions"


[[redirects]]
  from = "/api/diagnosis"
  to = "/.netlify/functions/diagnose"
  status = 200
